# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ASR.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tASR.proto\x12\x03\x41SR\"7\n\x18SpeechRecognitionMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\";\n\x18SpeechRecognitionRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0bspeechVoice\x18\x02 \x01(\x0c\"Q\n\x19SpeechRecognitionResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0ftranscribedText\x18\x02 \x01(\t\x12\x0f\n\x07isFinal\x18\x03 \x01(\x08\x32\x9f\x01\n\x03\x41SR\x12\x46\n\x04test\x12\x1d.ASR.SpeechRecognitionMessage\x1a\x1d.ASR.SpeechRecognitionMessage\"\x00\x12P\n\trecognize\x12\x1d.ASR.SpeechRecognitionRequest\x1a\x1e.ASR.SpeechRecognitionResponse\"\x00(\x01\x30\x01\x62\x06proto3')



_SPEECHRECOGNITIONMESSAGE = DESCRIPTOR.message_types_by_name['SpeechRecognitionMessage']
_SPEECHRECOGNITIONREQUEST = DESCRIPTOR.message_types_by_name['SpeechRecognitionRequest']
_SPEECHRECOGNITIONRESPONSE = DESCRIPTOR.message_types_by_name['SpeechRecognitionResponse']
SpeechRecognitionMessage = _reflection.GeneratedProtocolMessageType('SpeechRecognitionMessage', (_message.Message,), {
  'DESCRIPTOR' : _SPEECHRECOGNITIONMESSAGE,
  '__module__' : 'ASR_pb2'
  # @@protoc_insertion_point(class_scope:ASR.SpeechRecognitionMessage)
  })
_sym_db.RegisterMessage(SpeechRecognitionMessage)

SpeechRecognitionRequest = _reflection.GeneratedProtocolMessageType('SpeechRecognitionRequest', (_message.Message,), {
  'DESCRIPTOR' : _SPEECHRECOGNITIONREQUEST,
  '__module__' : 'ASR_pb2'
  # @@protoc_insertion_point(class_scope:ASR.SpeechRecognitionRequest)
  })
_sym_db.RegisterMessage(SpeechRecognitionRequest)

SpeechRecognitionResponse = _reflection.GeneratedProtocolMessageType('SpeechRecognitionResponse', (_message.Message,), {
  'DESCRIPTOR' : _SPEECHRECOGNITIONRESPONSE,
  '__module__' : 'ASR_pb2'
  # @@protoc_insertion_point(class_scope:ASR.SpeechRecognitionResponse)
  })
_sym_db.RegisterMessage(SpeechRecognitionResponse)

_ASR = DESCRIPTOR.services_by_name['ASR']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SPEECHRECOGNITIONMESSAGE._serialized_start=18
  _SPEECHRECOGNITIONMESSAGE._serialized_end=73
  _SPEECHRECOGNITIONREQUEST._serialized_start=75
  _SPEECHRECOGNITIONREQUEST._serialized_end=134
  _SPEECHRECOGNITIONRESPONSE._serialized_start=136
  _SPEECHRECOGNITIONRESPONSE._serialized_end=217
  _ASR._serialized_start=220
  _ASR._serialized_end=379
# @@protoc_insertion_point(module_scope)
