# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ASR_pb2 as ASR__pb2


class ASRStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.test = channel.unary_unary(
                '/ASR.ASR/test',
                request_serializer=ASR__pb2.SpeechRecognitionMessage.SerializeToString,
                response_deserializer=ASR__pb2.SpeechRecognitionMessage.FromString,
                )
        self.recognize = channel.stream_stream(
                '/ASR.ASR/recognize',
                request_serializer=ASR__pb2.SpeechRecognitionRequest.SerializeToString,
                response_deserializer=ASR__pb2.SpeechRecognitionResponse.FromString,
                )


class ASRServicer(object):
    """Missing associated documentation comment in .proto file."""

    def test(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def recognize(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ASRServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'test': grpc.unary_unary_rpc_method_handler(
                    servicer.test,
                    request_deserializer=ASR__pb2.SpeechRecognitionMessage.FromString,
                    response_serializer=ASR__pb2.SpeechRecognitionMessage.SerializeToString,
            ),
            'recognize': grpc.stream_stream_rpc_method_handler(
                    servicer.recognize,
                    request_deserializer=ASR__pb2.SpeechRecognitionRequest.FromString,
                    response_serializer=ASR__pb2.SpeechRecognitionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ASR.ASR', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ASR(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def test(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ASR.ASR/test',
            ASR__pb2.SpeechRecognitionMessage.SerializeToString,
            ASR__pb2.SpeechRecognitionMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def recognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ASR.ASR/recognize',
            ASR__pb2.SpeechRecognitionRequest.SerializeToString,
            ASR__pb2.SpeechRecognitionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
